import React, { useState } from 'react';
/* global MoudarEngine */

export default function CFIR2View({ project, strategies: strategiesProp, lang, onClose }) {
  const strategies = strategiesProp || [];
  const [citationsVisible, setCitationsVisible] = useState(false);

  // Defensive check to avoid blank page
  let evaluation;
  const defaultEval = {
    globalScore: 0,
    coveredConstructs: 0,
    totalConstructs: 39,
    domainScores: {
      innovation: { score: 0, label: lang === "fr" ? "Innovation" : "Innovation", constructs: [] },
      outerSetting: { score: 0, label: lang === "fr" ? "Contexte externe" : "Outer Setting", constructs: [] },
      innerSetting: { score: 0, label: lang === "fr" ? "Contexte interne" : "Inner Setting", constructs: [] },
      individuals: { score: 0, label: lang === "fr" ? "Individus" : "Individuals", constructs: [] },
      process: { score: 0, label: lang === "fr" ? "Processus" : "Process", constructs: [] }
    },
    criticalGaps: [],
    gaps: [],
    strengths: [],
    levelLabel: lang === "fr" ? "Non \u00E9valu\u00E9" : "Not evaluated",
    radarData: [],
    dimensions: {},
    citation: 'Damschroder LJ et al. (2022). Implementation Science, 17:75',
    version: '2.0'
  };
  try {
    if (!MoudarEngine.evaluateCFIR) {
      evaluation = defaultEval;
    } else {
      evaluation = MoudarEngine.evaluateCFIR(project, strategies, lang);
      evaluation.domainScores = evaluation.domainScores || defaultEval.domainScores;
      evaluation.criticalGaps = evaluation.criticalGaps || [];
      evaluation.radarData = evaluation.radarData || [];
      evaluation.dimensions = evaluation.dimensions || {};
      evaluation.levelLabel = evaluation.levelLabel || defaultEval.levelLabel;
    }
  } catch (e) {
    console.error("[MOUDAR] Erreur CFIR:", e);
    evaluation = defaultEval;
  }

  const domainColors = {
    innovation: '#3b82f6',
    outerSetting: '#10b981',
    innerSetting: '#8b5cf6',
    individuals: '#f59e0b',
    process: '#ef4444'
  };
  const domainIcons = {
    innovation: '\uD83D\uDCA1',
    outerSetting: '\uD83C\uDF0D',
    innerSetting: '\uD83C\uDFDB\uFE0F',
    individuals: '\uD83D\uDC64',
    process: '\u2699\uFE0F'
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-6xl w-full max-h-[90vh] overflow-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b p-4 flex justify-between items-center z-10">
          <div>
            <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
              {"\uD83C\uDFD7\uFE0F "}{lang === "fr" ? "\u00C9valuation CFIR 2.0" : "CFIR 2.0 Evaluation"}
              <span className="px-2 py-0.5 bg-green-100 text-green-700 text-xs rounded-full font-normal">Damschroder 2022</span>
            </h2>
            <p className="text-sm text-gray-500">
              5 {lang === "fr" ? "domaines" : "domains"} {"\u2022"} 39 constructs {"\u2022"} {lang === "fr" ? "Alignement exact CFIR 2.0" : "Exact CFIR 2.0 alignment"}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setCitationsVisible(!citationsVisible)}
              className="px-3 py-1.5 bg-blue-50 text-blue-700 rounded-lg text-sm hover:bg-blue-100"
              title={lang === "fr" ? "Voir les citations" : "View citations"}
            >
              {"\uD83D\uDCDA"} Cite
            </button>
            <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">{"\u2715"}</button>
          </div>
        </div>

        {/* Citations */}
        {citationsVisible && (
          <div className="mx-6 mt-4 p-4 bg-blue-50 rounded-xl border border-blue-200">
            <h4 className="font-bold text-blue-800 text-sm mb-2">
              {"\uD83D\uDCDA "}{lang === "fr" ? "Citations pour vos publications" : "Citations for your publications"}
            </h4>
            <div className="space-y-1 text-xs text-gray-700 font-mono">
              <p>{"\u2022"} Damschroder LJ, Reardon CM, Widerquist MAO, et al. (2022). Implementation Science, 17:75.</p>
              <p>{"\u2022"} Waltz TJ, Powell BJ, Fernandez ME, et al. (2019). Implementation Science, 14:50.</p>
              <p>{"\u2022"} Powell BJ, Waltz TJ, Chinman MJ, et al. (2015). Implementation Science, 10:21.</p>
              <p>{"\u2022"} Generated by MOUDAR&reg; v11.0 &mdash; AI-Powered IS Platform. &copy; 2025 Younes MOUDAR.</p>
            </div>
          </div>
        )}

        <div className="p-6">
          {/* Global Score */}
          <div className="text-center p-6 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl border border-indigo-200 mb-6">
            <div className="text-5xl font-bold text-indigo-700 mb-2">{evaluation.globalScore}%</div>
            <p className="text-gray-600">{lang === "fr" ? "Score CFIR 2.0 global" : "Global CFIR 2.0 Score"}</p>
            <p className="text-sm text-gray-500 mt-2">
              {evaluation.coveredConstructs || 0}/{evaluation.totalConstructs || 39} constructs {lang === "fr" ? "couverts" : "covered"}
            </p>
            <p className="text-xs text-gray-400 mt-1">
              {lang === "fr" ? "Bas\u00E9 sur" : "Based on"} Damschroder et al. (2022) {"\u2022"} CFIR-ERIC: Waltz et al. (2019)
            </p>
          </div>

          {/* Domain Scores */}
          <div className="grid md:grid-cols-5 gap-4 mb-6">
            {Object.keys(evaluation.domainScores || {}).map((domainId) => {
              const domain = evaluation.domainScores[domainId] || {};
              return (
                <div
                  key={domainId}
                  className="p-4 rounded-xl border"
                  style={{ borderColor: domainColors[domainId], backgroundColor: domainColors[domainId] + '10' }}
                >
                  <div className="text-lg mb-1">{domainIcons[domainId] || '\uD83D\uDCCB'}</div>
                  <div className="text-2xl font-bold" style={{ color: domainColors[domainId] }}>{domain.score || 0}%</div>
                  <div className="text-sm font-medium text-gray-700">{domain.label || domainId}</div>
                  <div className="text-xs text-gray-500">{domain.covered || 0}/{domain.total || 0} constructs</div>
                </div>
              );
            })}
          </div>

          {/* Critical Gaps */}
          {evaluation.criticalGaps && evaluation.criticalGaps.length > 0 && (
            <div className="mb-6 p-4 bg-red-50 rounded-xl border border-red-200">
              <h3 className="font-bold text-red-800 mb-3">
                {"\u26A0\uFE0F "}{lang === "fr" ? "Gaps critiques \u2014 Recommandations ERIC (Waltz et al. 2019)" : "Critical Gaps \u2014 ERIC Recommendations (Waltz et al. 2019)"}
              </h3>
              <div className="space-y-3">
                {(evaluation.criticalGaps || []).map((gap, i) => (
                  <div key={i} className="p-3 bg-white rounded-lg border border-red-100">
                    <div className="flex justify-between items-start">
                      <div>
                        <span className="font-medium text-red-700">{gap.construct || ""}</span>
                        <span className="text-gray-400 ml-2 text-xs">({gap.domain || ""})</span>
                      </div>
                      <span className="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded">
                        {lang === "fr" ? "Poids" : "Weight"}: {gap.weight}
                      </span>
                    </div>
                    <div className="text-blue-600 text-xs mt-1">
                      {"\uD83D\uDCA1 "}{gap.recommendation || ""}
                    </div>
                    {gap.ericStrategies && gap.ericStrategies.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1">
                        {gap.ericStrategies.map((es, j) => (
                          <span
                            key={j}
                            className={"px-2 py-0.5 rounded text-xs " + (es.level === 1 ? "bg-green-100 text-green-700" : "bg-yellow-100 text-yellow-700")}
                          >
                            {es.strategy} {es.level === 1 ? "\u2605" : "\u2606"}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Domain Details */}
          <div className="space-y-4">
            {Object.keys(evaluation.domainScores || {}).map((domainId) => {
              const domain = evaluation.domainScores[domainId] || {};
              return (
                <details key={domainId} className="border rounded-xl overflow-hidden">
                  <summary
                    className="p-4 cursor-pointer font-medium flex justify-between items-center"
                    style={{ backgroundColor: domainColors[domainId] + '10' }}
                  >
                    <span>{domainIcons[domainId] || '\uD83D\uDCCB'} {domain.label || domainId}</span>
                    <span className="font-bold" style={{ color: domainColors[domainId] }}>{domain.score || 0}%</span>
                  </summary>
                  <div className="p-4 bg-white">
                    {domain.description && <p className="text-xs text-gray-500 mb-3 italic">{domain.description}</p>}
                    <div className="grid gap-2">
                      {(domain.constructs || []).map((c) => {
                        const statusColor = c.status === 'strong' ? 'bg-green-100 text-green-700' : c.status === 'partial' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-500';
                        return (
                          <div
                            key={c.id}
                            className="flex justify-between items-center text-sm p-2 rounded hover:bg-gray-50"
                            title={c.cfir2Note || ''}
                          >
                            <div className="flex items-center gap-2">
                              <span className="text-xs text-gray-400 font-mono w-8">{c.id}</span>
                              <span className="text-gray-700">{c.name || ""}</span>
                              {c.cfir2Note && c.cfir2Note.indexOf('NEW') >= 0 && (
                                <span className="px-1 py-0 bg-blue-100 text-blue-600 text-xs rounded">NEW</span>
                              )}
                            </div>
                            <span className={"px-2 py-0.5 rounded text-xs " + statusColor}>
                              {c.coveredBy && c.coveredBy.length > 0 ? c.coveredBy.join(', ') : lang === 'fr' ? 'Non couvert' : 'Not covered'}
                            </span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </details>
              );
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-white border-t p-4 flex justify-between items-center">
          <span className="text-xs text-gray-400">
            CFIR 2.0 (Damschroder et al., 2022) {"\u2022"} CFIR-ERIC (Waltz et al., 2019) {"\u2022"} MOUDAR&reg; v11.0
          </span>
          <button onClick={onClose} className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200">
            {lang === "fr" ? "Fermer" : "Close"}
          </button>
        </div>
      </div>
    </div>
  );
}
