import React, { useState, useRef, useEffect } from 'react';
/* global MoudarEngine, StorageManager, DOMAINS, PHASES, SECTOR_TERMS, tObj, generateIntelligentProtocol, MoudarValidator, SemanticNLP, docx, saveAs, DemoGuide, SocialNetworkAnalyzer, ImplementationMonitor, GeoMapEngine, ScalingSimulator, LocalLLMEngine, RealtimeCollaboration, PowerPointExporter, DHIS2Connector, VoiceAssistant, selectedProjectId */

// ── Sub-view imports ────────────────────────────────────────
import TheoryOfChangeView from './TheoryOfChangeView';
import ScenarioComparatorView from './ScenarioComparatorView';
import KPIPanelView from './KPIPanelView';
import StakeholderMapModal from './StakeholderMapModal';
import TrainingPlanView from './TrainingPlanView';
import SuccessPredictionView from './SuccessPredictionView';
import BudgetEstimatorView from './BudgetEstimatorView';
import CountryIntelligenceView from './CountryIntelligenceView';
import CaseLibraryView from './CaseLibraryView';
import RiskAnalysisView from './RiskAnalysisView';
import ResearchExportsView from './ResearchExportsView';
import TornadoAnalysisView from './TornadoAnalysisView';
import PortfolioView from './PortfolioView';
import GanttTimelineView from './GanttTimelineView';
import CFIR2View from './CFIR2View';
import REAIMView from './REAIMView';
import ROICalculatorView from './ROICalculatorView';
import FundingProposalView from './FundingProposalView';
import MonitoringDashboardView from './MonitoringDashboardView';
import LogicModelView from './LogicModelView';
import MonteCarloView from './MonteCarloView';
import NLPBarrierAnalyzerView from './NLPBarrierAnalyzerView';
import PowerPointGeneratorView from './PowerPointGeneratorView';
import APIDocumentationView from './APIDocumentationView';
import CommunityHubView from './CommunityHubView';
import DataIntegrationsView from './DataIntegrationsView';
import XAIExplainerView from './XAIExplainerView';
import GlossaryView from './GlossaryView';
import CertificationView from './CertificationView';
import DocumentAnalyzerView from './DocumentAnalyzerView';

export default function WizardView({ existingProject, lang }) {
  const [step, setStep] = useState(existingProject && existingProject.protocol ? -1 : 0);
  const [answers, setAnswers] = useState(existingProject || {});
  const [protocol, setProtocol] = useState(existingProject && existingProject.protocol ? existingProject.protocol : null);
  const [saved, setSaved] = useState(false);
  const [currentProjectId, setCurrentProjectId] = useState(existingProject ? existingProject.id : null);
  const [isGenerating, setIsGenerating] = useState(false);

  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (existingProject && existingProject.tags && existingProject.tags.indexOf('gold_standard') !== -1 && !existingProject.protocol && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      console.log("[MOUDAR GOLD] Auto-g\u00e9n\u00e9ration du protocole pour projet Gold Standard");
      setTimeout(() => {
        setIsGenerating(true);
        setTimeout(() => {
          try {
            const result = generateIntelligentProtocol(existingProject, lang);
            if (result) {
              setProtocol(result);
              setStep(-1);
              const projectToSave = Object.assign({}, existingProject, { protocol: result, status: "protocol" });
              StorageManager.saveProject(projectToSave);
              console.log("[MOUDAR GOLD] \u2705 Protocole Gold g\u00e9n\u00e9r\u00e9 automatiquement!");
            }
          } catch (e) {
            console.error("[MOUDAR GOLD] Erreur auto-g\u00e9n\u00e9ration:", e);
          }
          setIsGenerating(false);
        }, 500);
      }, 800);
    }
  }, [existingProject]);

  // Modal states
  const [showTheory, setShowTheory] = useState(false);
  const [showScenarios, setShowScenarios] = useState(false);
  const [showKPIs, setShowKPIs] = useState(false);
  const [showStakeholders, setShowStakeholders] = useState(false);
  const [showTrainingPlan, setShowTrainingPlan] = useState(false);
  const [showSuccessPrediction, setShowSuccessPrediction] = useState(false);
  const [showBudgetEstimator, setShowBudgetEstimator] = useState(false);
  const [showCountryIntelligence, setShowCountryIntelligence] = useState(false);
  const [showCaseLibrary, setShowCaseLibrary] = useState(false);
  const [showRiskAnalysis, setShowRiskAnalysis] = useState(false);
  const [showTornadoAnalysis, setShowTornadoAnalysis] = useState(false);
  const [showCollaboration, setShowCollaboration] = useState(false);
  const [showLLMAnalyzer, setShowLLMAnalyzer] = useState(false);
  const [showPPTXExport, setShowPPTXExport] = useState(false);
  const [collaborators, setCollaborators] = useState([]);
  const [showSNA, setShowSNA] = useState(false);
  const [showMonitoring, setShowMonitoring] = useState(false);
  const [showGeoMap, setShowGeoMap] = useState(false);
  const [showScaling, setShowScaling] = useState(false);
  const [showDHIS2, setShowDHIS2] = useState(false);
  const [showVoiceAssistant, setShowVoiceAssistant] = useState(false);
  const [demoMode, setDemoMode] = useState(false);
  const [demoStep, setDemoStep] = useState(null);
  const [showClosedLoop, setShowClosedLoop] = useState(false);
  const [showPortfolio, setShowPortfolio] = useState(false);
  const [showResearchExports, setShowResearchExports] = useState(false);
  const [showGanttTimeline, setShowGanttTimeline] = useState(false);
  const [showCFIR2, setShowCFIR2] = useState(false);
  const [showREAIM, setShowREAIM] = useState(false);
  const [showROICalculator, setShowROICalculator] = useState(false);
  const [showFundingProposal, setShowFundingProposal] = useState(false);
  const [showMonitoringDashboard, setShowMonitoringDashboard] = useState(false);
  const [showLogicModel, setShowLogicModel] = useState(false);
  const [showMonteCarlo, setShowMonteCarlo] = useState(false);
  const [showNLPAnalyzer, setShowNLPAnalyzer] = useState(false);
  const [showPowerPointGenerator, setShowPowerPointGenerator] = useState(false);
  const [showAPIDocs, setShowAPIDocs] = useState(false);
  const [showCommunityHub, setShowCommunityHub] = useState(false);
  const [showDataIntegrations, setShowDataIntegrations] = useState(false);
  const [showXAIExplainer, setShowXAIExplainer] = useState(false);
  const [showGlossary, setShowGlossary] = useState(false);
  const [showCertification, setShowCertification] = useState(false);
  const [showDocumentAnalyzer, setShowDocumentAnalyzer] = useState(false);
  const [showAllTools, setShowAllTools] = useState(false);
  const [validationErrors, setValidationErrors] = useState(null);
  const [qualityScore, setQualityScore] = useState(null);

  const domainOptions = Object.entries(DOMAINS).map((entry) => ({
    value: entry[0],
    label: entry[1].icon + " " + tObj(entry[1], lang)
  }));
  const phaseOptions = Object.entries(PHASES).map((entry) => ({
    value: entry[0],
    label: entry[1].icon + " " + tObj(entry[1], lang),
    description: tObj(entry[1].description, lang)
  }));

  const countryOptions = [
    { value: "morocco", label: "\uD83C\uDDF2\uD83C\uDDE6 " + (lang === "fr" ? "Maroc" : "Morocco") },
    { value: "tunisia", label: "\uD83C\uDDF9\uD83C\uDDF3 " + (lang === "fr" ? "Tunisie" : "Tunisia") },
    { value: "algeria", label: "\uD83C\uDDE9\uD83C\uDDFF " + (lang === "fr" ? "Alg\u00e9rie" : "Algeria") },
    { value: "senegal", label: "\uD83C\uDDF8\uD83C\uDDF3 " + (lang === "fr" ? "S\u00e9n\u00e9gal" : "Senegal") },
    { value: "mali", label: "\uD83C\uDDF2\uD83C\uDDF1 " + (lang === "fr" ? "Mali" : "Mali") },
    { value: "cotedivoire", label: "\uD83C\uDDE8\uD83C\uDDEE " + (lang === "fr" ? "C\u00f4te d'Ivoire" : "Ivory Coast") },
    { value: "france", label: "\uD83C\uDDEB\uD83C\uDDF7 " + (lang === "fr" ? "France" : "France") },
    { value: "switzerland", label: "\uD83C\uDDE8\uD83C\uDDED " + (lang === "fr" ? "Suisse" : "Switzerland") },
    { value: "belgium", label: "\uD83C\uDDE7\uD83C\uDDEA " + (lang === "fr" ? "Belgique" : "Belgium") },
    { value: "canada", label: "\uD83C\uDDE8\uD83C\uDDE6 " + (lang === "fr" ? "Canada" : "Canada") },
    { value: "usa", label: "\uD83C\uDDFA\uD83C\uDDF8 " + (lang === "fr" ? "\u00c9tats-Unis" : "United States") },
    { value: "uk", label: "\uD83C\uDDEC\uD83C\uDDE7 " + (lang === "fr" ? "Royaume-Uni" : "United Kingdom") },
    { value: "other_hic", label: "\uD83C\uDF0D " + (lang === "fr" ? "Autre pays \u00e0 haut revenu" : "Other high-income country") },
    { value: "other_umic", label: "\uD83C\uDF0D " + (lang === "fr" ? "Autre pays \u00e0 revenu interm\u00e9diaire sup\u00e9rieur" : "Other upper-middle income") },
    { value: "other_lmic", label: "\uD83C\uDF0D " + (lang === "fr" ? "Autre pays \u00e0 revenu interm\u00e9diaire inf\u00e9rieur" : "Other lower-middle income") },
    { value: "other_lic", label: "\uD83C\uDF0D " + (lang === "fr" ? "Autre pays \u00e0 faible revenu" : "Other low-income country") }
  ];
  const settingOptions = [
    { value: "hospital", label: "\uD83C\uDFE5 " + (lang === "fr" ? "H\u00f4pital / CHU" : "Hospital / University Hospital") },
    { value: "clinic", label: "\uD83C\uDFE8 " + (lang === "fr" ? "Centre de sant\u00e9 / Clinique" : "Health Center / Clinic") },
    { value: "community", label: "\uD83C\uDFD8\uFE0F " + (lang === "fr" ? "Communaut\u00e9 / Terrain" : "Community / Field") },
    { value: "school", label: "\uD83C\uDFEB " + (lang === "fr" ? "\u00c9cole / Universit\u00e9" : "School / University") },
    { value: "workplace", label: "\uD83C\uDFE2 " + (lang === "fr" ? "Entreprise / Lieu de travail" : "Company / Workplace") },
    { value: "nursingHome", label: "\uD83C\uDFE0 " + (lang === "fr" ? "EHPAD / Maison de retraite" : "Nursing Home") },
    { value: "prison", label: "\uD83D\uDD12 " + (lang === "fr" ? "Milieu carc\u00e9ral" : "Prison / Correctional") },
    { value: "telehealth", label: "\uD83D\uDCBB " + (lang === "fr" ? "T\u00e9l\u00e9sant\u00e9 / \u00c0 distance" : "Telehealth / Remote") },
    { value: "rural", label: "\uD83C\uDF3E " + (lang === "fr" ? "Zone rurale" : "Rural Area") },
    { value: "urban", label: "\uD83C\uDFD9\uFE0F " + (lang === "fr" ? "Zone urbaine" : "Urban Area") },
    { value: "mixed", label: "\uD83D\uDD00 " + (lang === "fr" ? "Mixte (plusieurs types)" : "Mixed (multiple types)") }
  ];
  const scopeOptions = [
    { value: "pilot", label: "\uD83D\uDD2C " + (lang === "fr" ? "Pilote (1-3 sites)" : "Pilot (1-3 sites)") },
    { value: "local", label: "\uD83D\uDCCD " + (lang === "fr" ? "Local (1 ville/district)" : "Local (1 city/district)") },
    { value: "regional", label: "\uD83D\uDDFA\uFE0F " + (lang === "fr" ? "R\u00e9gional (1 r\u00e9gion/province)" : "Regional (1 region/province)") },
    { value: "national", label: "\uD83C\uDFDB\uFE0F " + (lang === "fr" ? "National" : "National") },
    { value: "multi_country", label: "\uD83C\uDF10 " + (lang === "fr" ? "Multi-pays" : "Multi-country") }
  ];
  const teamSizeOptions = [
    { value: "1-2", label: "\uD83D\uDC64 1-2 " + (lang === "fr" ? "personnes" : "people") },
    { value: "3-5", label: "\uD83D\uDC65 3-5 " + (lang === "fr" ? "personnes" : "people") },
    { value: "6-10", label: "\uD83D\uDC65 6-10 " + (lang === "fr" ? "personnes" : "people") },
    { value: "11-20", label: "\uD83D\uDC65 11-20 " + (lang === "fr" ? "personnes" : "people") },
    { value: "21-50", label: "\uD83D\uDC65 21-50 " + (lang === "fr" ? "personnes" : "people") },
    { value: "50+", label: "\uD83D\uDC65 50+ " + (lang === "fr" ? "personnes" : "people") }
  ];
  const timelineOptions = [
    { value: "3", label: "\u23F1\uFE0F 3 " + (lang === "fr" ? "mois (pilote rapide)" : "months (quick pilot)") },
    { value: "6", label: "\u23F1\uFE0F 6 " + (lang === "fr" ? "mois" : "months") },
    { value: "12", label: "\uD83D\uDCC5 12 " + (lang === "fr" ? "mois (1 an)" : "months (1 year)") },
    { value: "18", label: "\uD83D\uDCC5 18 " + (lang === "fr" ? "mois" : "months") },
    { value: "24", label: "\uD83D\uDCC5 24 " + (lang === "fr" ? "mois (2 ans)" : "months (2 years)") },
    { value: "36", label: "\uD83D\uDCC5 36 " + (lang === "fr" ? "mois (3 ans)" : "months (3 years)") },
    { value: "48+", label: "\uD83D\uDCC5 48+ " + (lang === "fr" ? "mois (>3 ans)" : "months (>3 years)") }
  ];
  const budgetOptions = [
    { value: "unknown", label: "\u2753 " + (lang === "fr" ? "Non d\u00e9fini / \u00c0 d\u00e9terminer" : "Not defined / TBD") },
    { value: "<10k", label: "\uD83D\uDCB0 < 10,000 \u20ac/$" },
    { value: "10-50k", label: "\uD83D\uDCB0 10,000 - 50,000 \u20ac/$" },
    { value: "50-100k", label: "\uD83D\uDCB0\uD83D\uDCB0 50,000 - 100,000 \u20ac/$" },
    { value: "100-500k", label: "\uD83D\uDCB0\uD83D\uDCB0 100,000 - 500,000 \u20ac/$" },
    { value: "500k-1m", label: "\uD83D\uDCB0\uD83D\uDCB0\uD83D\uDCB0 500,000 - 1M \u20ac/$" },
    { value: ">1m", label: "\uD83D\uDCB0\uD83D\uDCB0\uD83D\uDCB0 > 1M \u20ac/$" }
  ];
  const experienceOptions = [
    { value: "none", label: "\uD83C\uDD95 " + (lang === "fr" ? "Premi\u00e8re exp\u00e9rience en impl\u00e9mentation" : "First implementation experience") },
    { value: "some", label: "\uD83D\uDCDA " + (lang === "fr" ? "Quelques projets similaires (1-3)" : "Some similar projects (1-3)") },
    { value: "experienced", label: "\u2B50 " + (lang === "fr" ? "Exp\u00e9rience significative (4-10 projets)" : "Significant experience (4-10 projects)") },
    { value: "expert", label: "\uD83C\uDFC6 " + (lang === "fr" ? "Expert en impl\u00e9mentation (10+ projets)" : "Implementation expert (10+ projects)") }
  ];
  const barrierCategoryOptions = [
    { value: "knowledge", label: "\uD83D\uDCDA " + (lang === "fr" ? "Connaissances / Formation insuffisante" : "Knowledge / Insufficient training") },
    { value: "attitudes", label: "\uD83E\uDDE0 " + (lang === "fr" ? "Attitudes / R\u00e9sistance au changement" : "Attitudes / Resistance to change") },
    { value: "resources", label: "\uD83D\uDCB5 " + (lang === "fr" ? "Ressources (temps, argent, personnel)" : "Resources (time, money, staff)") },
    { value: "infrastructure", label: "\uD83C\uDFD7\uFE0F " + (lang === "fr" ? "Infrastructure / \u00c9quipement / IT" : "Infrastructure / Equipment / IT") },
    { value: "leadership", label: "\uD83D\uDC54 " + (lang === "fr" ? "Leadership / Soutien institutionnel faible" : "Leadership / Weak institutional support") },
    { value: "culture", label: "\uD83C\uDF0D " + (lang === "fr" ? "Culture / Stigma / Croyances" : "Culture / Stigma / Beliefs") },
    { value: "policy", label: "\uD83D\uDCDC " + (lang === "fr" ? "Politiques / R\u00e9glementation" : "Policies / Regulations") },
    { value: "coordination", label: "\uD83D\uDD17 " + (lang === "fr" ? "Coordination / Communication" : "Coordination / Communication") },
    { value: "turnover", label: "\uD83D\uDD04 " + (lang === "fr" ? "Rotation du personnel / Instabilit\u00e9" : "Staff turnover / Instability") },
    { value: "complexity", label: "\uD83E\uDDE9 " + (lang === "fr" ? "Complexit\u00e9 de l'intervention" : "Intervention complexity") }
  ];
  const outcomeOptions = [
    { value: "acceptability", label: "\u2705 " + (lang === "fr" ? "Acceptabilit\u00e9 par les acteurs" : "Acceptability by stakeholders") },
    { value: "adoption", label: "\uD83D\uDCC8 " + (lang === "fr" ? "Adoption de la pratique" : "Practice adoption") },
    { value: "fidelity", label: "\uD83C\uDFAF " + (lang === "fr" ? "Fid\u00e9lit\u00e9 \u00e0 l'intervention" : "Intervention fidelity") },
    { value: "coverage", label: "\uD83D\uDCCA " + (lang === "fr" ? "Couverture / P\u00e9n\u00e9tration" : "Coverage / Penetration") },
    { value: "sustainability", label: "\u267B\uFE0F " + (lang === "fr" ? "P\u00e9rennit\u00e9 / Durabilit\u00e9" : "Sustainability") },
    { value: "cost", label: "\uD83D\uDCB0 " + (lang === "fr" ? "Co\u00fbt-efficacit\u00e9" : "Cost-effectiveness") },
    { value: "patient_outcomes", label: "\u2764\uFE0F " + (lang === "fr" ? "Am\u00e9lioration clinique des b\u00e9n\u00e9ficiaires" : "Clinical improvement of beneficiaries") },
    { value: "equity", label: "\u2696\uFE0F " + (lang === "fr" ? "\u00c9quit\u00e9 d'acc\u00e8s" : "Access equity") }
  ];

  const questions = [
    { id: "title", type: "text", phase: 1, phaseLabel: lang === "fr" ? "\uD83D\uDCCB Identification" : "\uD83D\uDCCB Identification", q: lang === "fr" ? "Titre du projet" : "Project title", placeholder: lang === "fr" ? "Ex: Int\u00e9gration du programme mhGAP dans 45 centres de sant\u00e9 primaire de la r\u00e9gion Souss-Massa" : "Ex: Integration of mhGAP program in 45 primary health centers in the Souss-Massa region", help: lang === "fr" ? "Un titre clair et descriptif (minimum 10 caract\u00e8res, 3 mots)" : "A clear and descriptive title (minimum 10 characters, 3 words)", required: true },
    { id: "organization", type: "text", phase: 1, q: lang === "fr" ? "Organisation porteuse" : "Lead organization", placeholder: lang === "fr" ? "Ex: Direction R\u00e9gionale de la Sant\u00e9 Souss-Massa, Minist\u00e8re de la Sant\u00e9" : "Ex: Regional Health Directorate, Ministry of Health", help: lang === "fr" ? "Nom complet de l'organisation responsable du projet" : "Full name of the organization responsible for the project", required: true },
    { id: "country", type: "select", phase: 1, q: lang === "fr" ? "Pays d'impl\u00e9mentation" : "Implementation country", options: countryOptions, help: lang === "fr" ? "Le pays d\u00e9termine le niveau de ressources et adapte les recommandations" : "Country determines resource level and adapts recommendations", required: true },
    { id: "domain", type: "select", phase: 1, q: lang === "fr" ? "Domaine d'intervention" : "Intervention domain", options: domainOptions, help: lang === "fr" ? "Le domaine influence les strat\u00e9gies et barri\u00e8res typiques" : "Domain influences typical strategies and barriers", required: true },
    { id: "context", type: "textarea", phase: 2, phaseLabel: lang === "fr" ? "\uD83C\uDFE2 Contexte" : "\uD83C\uDFE2 Context", q: lang === "fr" ? "Contexte et probl\u00e9matique" : "Context and problem statement", placeholder: lang === "fr" ? "D\u00e9crivez en d\u00e9tail:\n\u2022 La situation actuelle et ses lacunes\n\u2022 Les donn\u00e9es \u00e9pid\u00e9miologiques ou statistiques pertinentes\n\u2022 Le probl\u00e8me que vous cherchez \u00e0 r\u00e9soudre\n\u2022 Les tentatives pr\u00e9c\u00e9dentes (succ\u00e8s/\u00e9checs)\n\u2022 L'urgence ou la priorit\u00e9 du changement" : "Describe in detail:\n\u2022 Current situation and gaps\n\u2022 Relevant epidemiological or statistical data\n\u2022 The problem you're trying to solve\n\u2022 Previous attempts (successes/failures)\n\u2022 Urgency or priority of change", help: lang === "fr" ? "Minimum 100 caract\u00e8res. Plus vous d\u00e9taillez, plus les recommandations seront pr\u00e9cises." : "Minimum 100 characters. More detail means more precise recommendations.", rows: 6, required: true },
    { id: "settingType", type: "select", phase: 2, q: lang === "fr" ? "Type de structure / contexte" : "Setting type / context", options: settingOptions, help: lang === "fr" ? "Le type de structure influence les strat\u00e9gies adapt\u00e9es" : "Setting type influences appropriate strategies", required: true },
    { id: "settingCount", type: "number", phase: 2, q: lang === "fr" ? "Nombre de sites / structures concern\u00e9s" : "Number of sites / facilities involved", placeholder: lang === "fr" ? "Ex: 45" : "Ex: 45", help: lang === "fr" ? "Combien de sites seront impliqu\u00e9s dans l'impl\u00e9mentation?" : "How many sites will be involved in implementation?", min: 1, max: 10000, required: true },
    { id: "geographicScope", type: "select", phase: 2, q: lang === "fr" ? "\u00c9tendue g\u00e9ographique" : "Geographic scope", options: scopeOptions, help: lang === "fr" ? "L'\u00e9tendue g\u00e9ographique influence la complexit\u00e9 logistique" : "Geographic scope influences logistical complexity", required: true },
    { id: "population", type: "textarea", phase: 3, phaseLabel: lang === "fr" ? "\uD83C\uDFAF Population & \u00c9quipe" : "\uD83C\uDFAF Population & Team", q: lang === "fr" ? "Population cible de l'intervention" : "Target population for the intervention", placeholder: lang === "fr" ? "Ex: 200 infirmiers g\u00e9n\u00e9ralistes dans 45 centres de sant\u00e9 primaire, majoritairement f\u00e9minins (75%), \u00e2ge moyen 35 ans, exp\u00e9rience moyenne 8 ans en soins primaires, formation initiale de 3 ans" : "Ex: 200 general nurses in 45 primary health centers, mostly female (75%), average age 35, average 8 years experience in primary care, 3-year initial training", help: lang === "fr" ? "D\u00e9crivez qui sera directement affect\u00e9 par l'intervention (nombre, caract\u00e9ristiques)" : "Describe who will be directly affected by the intervention (number, characteristics)", rows: 3, required: true },
    { id: "populationSize", type: "number", phase: 3, q: lang === "fr" ? "Nombre total de personnes cibl\u00e9es" : "Total number of people targeted", placeholder: lang === "fr" ? "Ex: 200" : "Ex: 200", help: lang === "fr" ? "Nombre approximatif de personnes directement concern\u00e9es" : "Approximate number of people directly involved", min: 1, required: true },
    { id: "beneficiaries", type: "textarea", phase: 3, q: lang === "fr" ? "B\u00e9n\u00e9ficiaires finaux (si diff\u00e9rents de la population cible)" : "End beneficiaries (if different from target population)", placeholder: lang === "fr" ? "Ex: 50,000 patients adultes avec troubles mentaux courants (d\u00e9pression, anxi\u00e9t\u00e9) dans la zone de couverture des 45 centres de sant\u00e9" : "Ex: 50,000 adult patients with common mental disorders (depression, anxiety) in the coverage area of the 45 health centers", help: lang === "fr" ? "Les personnes qui b\u00e9n\u00e9ficieront indirectement du projet (patients, usagers, etc.)" : "People who will indirectly benefit from the project (patients, users, etc.)", rows: 2, required: false },
    { id: "teamSize", type: "select", phase: 3, q: lang === "fr" ? "Taille de l'\u00e9quipe projet" : "Project team size", options: teamSizeOptions, help: lang === "fr" ? "Nombre de personnes dans l'\u00e9quipe de coordination/impl\u00e9mentation" : "Number of people in the coordination/implementation team", required: true },
    { id: "objectives", type: "textarea", phase: 4, phaseLabel: lang === "fr" ? "\uD83C\uDFAF Objectifs" : "\uD83C\uDFAF Objectives", q: lang === "fr" ? "Objectifs du projet" : "Project objectives", placeholder: lang === "fr" ? "Objectif g\u00e9n\u00e9ral:\n\u2022 Am\u00e9liorer la d\u00e9tection et prise en charge des troubles mentaux courants dans les centres de sant\u00e9 primaire\n\nObjectifs sp\u00e9cifiques:\n1. Former 80% des infirmiers au protocole mhGAP d'ici 12 mois\n2. Augmenter le taux de d\u00e9tection des troubles d\u00e9pressifs de 15% \u00e0 45%\n3. R\u00e9duire le d\u00e9lai de prise en charge de 3 mois \u00e0 2 semaines" : "General objective:\n\u2022 Improve detection and management of common mental disorders in primary health centers\n\nSpecific objectives:\n1. Train 80% of nurses in mhGAP protocol within 12 months\n2. Increase depression detection rate from 15% to 45%\n3. Reduce time to treatment from 3 months to 2 weeks", help: lang === "fr" ? "Formulez des objectifs SMART (Sp\u00e9cifiques, Mesurables, Atteignables, R\u00e9alistes, Temporels)" : "Formulate SMART objectives (Specific, Measurable, Achievable, Realistic, Time-bound)", rows: 6, required: true },
    { id: "expectedOutcomes", type: "multiselect", phase: 4, q: lang === "fr" ? "R\u00e9sultats d'impl\u00e9mentation attendus (s\u00e9lectionnez 2-5)" : "Expected implementation outcomes (select 2-5)", options: outcomeOptions, help: lang === "fr" ? "Quels indicateurs d'impl\u00e9mentation allez-vous mesurer?" : "Which implementation indicators will you measure?", minSelect: 2, maxSelect: 5, required: true },
    { id: "phase", type: "select", phase: 4, q: lang === "fr" ? "Phase actuelle du projet (EPIS)" : "Current project phase (EPIS)", options: phaseOptions, showDescription: true, help: lang === "fr" ? "\u00c0 quelle \u00e9tape en \u00eates-vous dans le cycle d'impl\u00e9mentation?" : "What stage are you at in the implementation cycle?", required: true },
    { id: "barriers", type: "textarea", phase: 5, phaseLabel: lang === "fr" ? "\u26A0\uFE0F Barri\u00e8res & Facilitateurs" : "\u26A0\uFE0F Barriers & Facilitators", q: lang === "fr" ? "Barri\u00e8res et d\u00e9fis anticip\u00e9s" : "Anticipated barriers and challenges", placeholder: lang === "fr" ? "D\u00e9crivez les obstacles attendus:\n\u2022 Individuels: r\u00e9sistance des soignants, manque de temps, peur du changement\n\u2022 Organisationnels: surcharge de travail, absence de supervision, rotation du personnel\n\u2022 Syst\u00e9miques: financement incertain, politiques non align\u00e9es, absence de donn\u00e9es\n\u2022 Culturels: stigma autour de la sant\u00e9 mentale, croyances traditionnelles" : "Describe expected obstacles:\n\u2022 Individual: staff resistance, lack of time, fear of change\n\u2022 Organizational: workload, lack of supervision, staff turnover\n\u2022 Systemic: uncertain funding, misaligned policies, lack of data\n\u2022 Cultural: mental health stigma, traditional beliefs", help: lang === "fr" ? "Minimum 50 caract\u00e8res. Plus vous identifiez de barri\u00e8res, plus les strat\u00e9gies seront cibl\u00e9es." : "Minimum 50 characters. More barriers identified means more targeted strategies.", rows: 5, required: true },
    { id: "barrierCategories", type: "multiselect", phase: 5, q: lang === "fr" ? "Cat\u00e9gories de barri\u00e8res principales (s\u00e9lectionnez 1-5)" : "Main barrier categories (select 1-5)", options: barrierCategoryOptions, help: lang === "fr" ? "Cochez les cat\u00e9gories de barri\u00e8res les plus importantes" : "Check the most important barrier categories", minSelect: 1, maxSelect: 5, required: true },
    { id: "facilitators", type: "textarea", phase: 5, q: lang === "fr" ? "Facilitateurs et atouts existants" : "Existing facilitators and assets", placeholder: lang === "fr" ? "Ex: Soutien du Minist\u00e8re de la Sant\u00e9, 5 champions locaux d\u00e9j\u00e0 identifi\u00e9s, budget de 150,000\u20ac allou\u00e9, exp\u00e9rience r\u00e9ussie dans 2 r\u00e9gions pilotes, partenariat avec l'OMS" : "Ex: Ministry of Health support, 5 local champions already identified, \u20ac150,000 budget allocated, successful experience in 2 pilot regions, WHO partnership", help: lang === "fr" ? "Quels atouts pouvez-vous mobiliser pour r\u00e9ussir?" : "What assets can you leverage for success?", rows: 3, required: false },
    { id: "timeline", type: "select", phase: 6, phaseLabel: lang === "fr" ? "\uD83D\uDCC5 Ressources & Planning" : "\uD83D\uDCC5 Resources & Planning", q: lang === "fr" ? "Dur\u00e9e estim\u00e9e du projet" : "Estimated project duration", options: timelineOptions, help: lang === "fr" ? "La dur\u00e9e influence les strat\u00e9gies et le s\u00e9quen\u00e7age des activit\u00e9s" : "Duration influences strategies and activity sequencing", required: true },
    { id: "budget", type: "select", phase: 6, q: lang === "fr" ? "Budget approximatif" : "Approximate budget", options: budgetOptions, help: lang === "fr" ? "Le budget influence les strat\u00e9gies recommand\u00e9es (certaines sont co\u00fbteuses)" : "Budget influences recommended strategies (some are expensive)", required: false },
    { id: "experience", type: "select", phase: 6, q: lang === "fr" ? "Exp\u00e9rience pr\u00e9alable en science de l'impl\u00e9mentation" : "Prior implementation science experience", options: experienceOptions, help: lang === "fr" ? "Votre niveau d'exp\u00e9rience influence la complexit\u00e9 des recommandations" : "Your experience level influences recommendation complexity", required: false },
    { id: "additionalInfo", type: "textarea", phase: 6, q: lang === "fr" ? "Informations compl\u00e9mentaires (optionnel)" : "Additional information (optional)", placeholder: lang === "fr" ? "Ajoutez toute information pertinente non couverte par les questions pr\u00e9c\u00e9dentes:\n\u2022 Contraintes sp\u00e9cifiques\n\u2022 Partenaires cl\u00e9s\n\u2022 Risques identifi\u00e9s\n\u2022 Questions particuli\u00e8res" : "Add any relevant information not covered by previous questions:\n\u2022 Specific constraints\n\u2022 Key partners\n\u2022 Identified risks\n\u2022 Specific questions", help: lang === "fr" ? "Informations suppl\u00e9mentaires pour affiner les recommandations" : "Additional information to refine recommendations", rows: 4, required: false }
  ];

  const wizardPhases = [
    { id: 1, name: lang === "fr" ? "Identification" : "Identification", icon: "\uD83D\uDCCB", questions: questions.filter((q) => q.phase === 1).map((q) => q.id) },
    { id: 2, name: lang === "fr" ? "Contexte" : "Context", icon: "\uD83C\uDFE2", questions: questions.filter((q) => q.phase === 2).map((q) => q.id) },
    { id: 3, name: lang === "fr" ? "Population" : "Population", icon: "\uD83C\uDFAF", questions: questions.filter((q) => q.phase === 3).map((q) => q.id) },
    { id: 4, name: lang === "fr" ? "Objectifs" : "Objectives", icon: "\uD83C\uDFAF", questions: questions.filter((q) => q.phase === 4).map((q) => q.id) },
    { id: 5, name: lang === "fr" ? "Barri\u00e8res" : "Barriers", icon: "\u26A0\uFE0F", questions: questions.filter((q) => q.phase === 5).map((q) => q.id) },
    { id: 6, name: lang === "fr" ? "Ressources" : "Resources", icon: "\uD83D\uDCC5", questions: questions.filter((q) => q.phase === 6).map((q) => q.id) }
  ];

  const generateProtocol = () => {
    setIsGenerating(true);
    setValidationErrors(null);
    setTimeout(() => {
      try {
        if (window.MoudarValidator) {
          const validation = MoudarValidator.validateProject(answers, lang);
          setQualityScore(validation.qualityScore);
          if (!validation.valid) {
            console.warn("[MOUDAR v9.0] Validation: certains champs incomplets, g\u00e9n\u00e9ration quand m\u00eame...", validation.errors);
          }
        }
        console.log("[MOUDAR v9.0] G\u00e9n\u00e9ration du protocole en cours...");
        const result = generateIntelligentProtocol(answers, lang);
        if (result) {
          setProtocol(result);
          setStep(-1);
          const projectToSave = Object.assign({}, answers, { id: currentProjectId, protocol: result, status: "protocol" });
          const savedProject = StorageManager.saveProject(projectToSave);
          setCurrentProjectId(savedProject.id);
          setSaved(true);
          setTimeout(() => { setSaved(false); }, 2000);
          console.log("[MOUDAR v9.0] \u2705 Protocole g\u00e9n\u00e9r\u00e9 avec succ\u00e8s!");
        } else {
          console.error("[MOUDAR v9.0] Erreur: protocole vide");
          alert(lang === "fr" ? "Erreur lors de la g\u00e9n\u00e9ration. Veuillez r\u00e9essayer." : "Generation error. Please try again.");
        }
      } catch (e) {
        console.error("[MOUDAR v9.0] Erreur de g\u00e9n\u00e9ration:", e);
        alert(lang === "fr" ? "Erreur: " + e.message : "Error: " + e.message);
      } finally {
        setIsGenerating(false);
      }
    }, 100);
  };

  const validateFieldOnChange = (fieldId, value) => {
    if (window.MoudarValidator) {
      MoudarValidator.validateField(fieldId, value, lang);
      const tempAnswers = Object.assign({}, answers);
      tempAnswers[fieldId] = value;
      const validation = MoudarValidator.validateProject(tempAnswers, lang);
      setQualityScore(validation.qualityScore);
    }
  };

  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [feedbackRating, setFeedbackRating] = useState(4);
  const [feedbackAccepted, setFeedbackAccepted] = useState(true);
  const [lastRecId, setLastRecId] = useState(null);

  const saveProject = () => {
    const projectToSave = Object.assign({}, answers, { id: currentProjectId, protocol: protocol, status: protocol ? "protocol" : "draft" });
    const savedProject = StorageManager.saveProject(projectToSave);
    setCurrentProjectId(savedProject.id);
    setSaved(true);
    if (protocol && protocol.aiConfidence && protocol.aiRawRecommendations) {
      setLastRecId((protocol.aiRawRecommendations.metadata || {}).recommendationId || 'REC_' + Date.now());
      setTimeout(() => { setSaved(false); setShowFeedbackModal(true); }, 1500);
    } else {
      setTimeout(() => { setSaved(false); }, 2000);
    }
  };

  const submitFeedback = () => {
    if (lastRecId && protocol && protocol.aiRawRecommendations) {
      let selectedStrategies = [];
      if (protocol.aiRawRecommendations.recommendations && protocol.aiRawRecommendations.recommendations.strategies ? protocol.aiRawRecommendations.recommendations.strategies.top : null) {
        selectedStrategies = protocol.aiRawRecommendations.recommendations.strategies.top.map((s) => s.id);
      }
      MoudarEngine.recordFeedback(lastRecId, {
        accepted: feedbackAccepted, modified: !feedbackAccepted, rating: feedbackRating, outcome: null,
        context: { project: protocol.aiRawRecommendations.input, selectedStrategies, confidence: protocol.aiConfidence }
      });
      console.log("\u2705 Feedback enregistr\u00e9 pour", lastRecId, "- Rating:", feedbackRating, "- Accepted:", feedbackAccepted);
    }
    setShowFeedbackModal(false);
    setFeedbackRating(4);
    setFeedbackAccepted(true);
  };

  const skipFeedback = () => { setShowFeedbackModal(false); setFeedbackRating(4); setFeedbackAccepted(true); };

  const calibrateAI = () => {
    const result = MoudarEngine.calibrateFromFeedback({ learningRate: 0.1, minSamples: 3 });
    if (result.adjusted) {
      alert(lang === "fr" ? "\u2705 Moteur IA recalibr\u00e9!\n" + result.strategiesUpdated + " strat\u00e9gies ajust\u00e9es.\n" + result.totalAdjustments + " poids modifi\u00e9s." : "\u2705 AI Engine recalibrated!\n" + result.strategiesUpdated + " strategies adjusted.\n" + result.totalAdjustments + " weights modified.");
    } else {
      alert(lang === "fr" ? "\u26A0\uFE0F Pas assez de donn\u00e9es pour recalibrer.\nContinuez \u00e0 utiliser Moudar pour am\u00e9liorer les recommandations." : "\u26A0\uFE0F Not enough data to recalibrate.\nKeep using Moudar to improve recommendations.");
    }
  };

  const FeedbackModal = () => {
    if (!showFeedbackModal) return null;
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 transform transition-all">
          <div className="text-center mb-6">
            <div className="text-4xl mb-2">{"\uD83E\uDD16"}</div>
            <h3 className="text-xl font-bold text-gray-800">{lang === "fr" ? "Aidez Moudar \u00e0 s'am\u00e9liorer" : "Help Moudar improve"}</h3>
            <p className="text-gray-600 text-sm mt-2">{lang === "fr" ? "Votre feedback permet d'ajuster l'algorithme" : "Your feedback helps calibrate the algorithm"}</p>
          </div>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">{lang === "fr" ? "Les recommandations sont pertinentes ?" : "Are recommendations relevant?"}</label>
              <div className="flex gap-3">
                <button onClick={() => setFeedbackAccepted(true)} className={"flex-1 py-3 rounded-lg font-medium transition " + (feedbackAccepted ? "bg-green-500 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200")}>{"\u2713 "}{lang === "fr" ? "Oui" : "Yes"}</button>
                <button onClick={() => setFeedbackAccepted(false)} className={"flex-1 py-3 rounded-lg font-medium transition " + (!feedbackAccepted ? "bg-red-500 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200")}>{"\u2717 "}{lang === "fr" ? "Non" : "No"}</button>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">{lang === "fr" ? "Note globale" : "Overall rating"}{": "}<span className="text-indigo-600 font-bold">{feedbackRating}/5</span></label>
              <div className="flex justify-center gap-2">
                {[1, 2, 3, 4, 5].map((n) => (
                  <button key={n} onClick={() => setFeedbackRating(n)} className={"w-10 h-10 rounded-full text-xl transition " + (n <= feedbackRating ? "bg-yellow-400" : "bg-gray-200")}>{"\u2605"}</button>
                ))}
              </div>
            </div>
          </div>
          <div className="flex gap-3 mt-6">
            <button onClick={skipFeedback} className="flex-1 py-3 rounded-lg font-medium bg-gray-100 text-gray-600 hover:bg-gray-200 transition">{lang === "fr" ? "Plus tard" : "Later"}</button>
            <button onClick={submitFeedback} className="flex-1 py-3 rounded-lg font-medium bg-gradient-to-r from-indigo-500 to-purple-500 text-white hover:from-indigo-600 hover:to-purple-600 transition">{lang === "fr" ? "Envoyer" : "Submit"}</button>
          </div>
          <p className="text-xs text-gray-400 text-center mt-4">{lang === "fr" ? "Ce feedback am\u00e9liore les recommandations futures" : "This feedback improves future recommendations"}</p>
        </div>
      </div>
    );
  };

  const exportWord = () => {
    if (!protocol) { alert(lang === "fr" ? "Aucun protocole \u00e0 exporter" : "No protocol to export"); return; }
    try {
      const projectTitle = answers.title || (lang === "fr" ? "Protocole d'implementation" : "Implementation protocol");
      const orgLine = (answers.organization || "") + " - Moudar v8.0";
      const domainLabel = answers.domain && DOMAINS[answers.domain] ? tObj(DOMAINS[answers.domain], lang) : "-";
      let phaseLabel = "-";
      if (answers.phase === "exploration") phaseLabel = lang === "fr" ? "Exploration" : "Exploration";
      else if (answers.phase === "preparation") phaseLabel = lang === "fr" ? "Preparation" : "Preparation";
      else if (answers.phase === "implementation") phaseLabel = lang === "fr" ? "Implementation" : "Implementation";
      else if (answers.phase === "sustainment") phaseLabel = lang === "fr" ? "Perennisation" : "Sustainment";
      const populationText = answers.population || "-";
      const contextText = answers.context || "-";
      const barriersText = answers.barriers || "-";
      const sectorTerms = SECTOR_TERMS[answers.domain] || SECTOR_TERMS["default"];
      const autoSummary = protocol.autoSummary || null;
      const frameworksList = protocol.frameworks || [];
      const strategiesList = protocol.strategies || [];
      const outcomesList = protocol.outcomes || [];
      const recommendationsList = protocol.recommendations || [];
      const children = [];
      children.push(new docx.Paragraph({ text: projectTitle, heading: docx.HeadingLevel.TITLE, alignment: docx.AlignmentType.CENTER }));
      children.push(new docx.Paragraph({ text: orgLine, alignment: docx.AlignmentType.CENTER }));
      children.push(new docx.Paragraph({ text: new Date().toLocaleDateString(), alignment: docx.AlignmentType.CENTER }));
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "1. Resume du projet" : "1. Project summary", heading: docx.HeadingLevel.HEADING_1 }));
      if (lang === "fr") {
        const programLbl = sectorTerms && sectorTerms.program && sectorTerms.program.fr ? sectorTerms.program.fr : "programme / intervention";
        const actorsLbl = sectorTerms && sectorTerms.actors && sectorTerms.actors.fr ? sectorTerms.actors.fr : "beneficiaires";
        children.push(new docx.Paragraph({ text: autoSummary || "Ce " + programLbl + " vise a ameliorer les resultats pour " + (populationText !== "-" ? populationText : "les " + actorsLbl) + " dans le domaine de " + domainLabel + ", en phase " + phaseLabel + "." }));
        children.push(new docx.Paragraph({ text: "" }));
        children.push(new docx.Paragraph({ text: "Ce document propose un squelette de protocole d'implementation pour ce projet." }));
        children.push(new docx.Paragraph({ text: "" }));
        children.push(new docx.Paragraph({ text: "Contexte (resume) : " + contextText }));
      } else {
        const programLblEn = sectorTerms && sectorTerms.program && sectorTerms.program.en ? sectorTerms.program.en : "program / intervention";
        const actorsLblEn = sectorTerms && sectorTerms.actors && sectorTerms.actors.en ? sectorTerms.actors.en : "beneficiaries";
        children.push(new docx.Paragraph({ text: autoSummary || "This " + programLblEn + " aims to improve outcomes for " + (populationText !== "-" ? populationText : "the " + actorsLblEn) + " in the domain of " + domainLabel + ", in the " + phaseLabel + " phase." }));
        children.push(new docx.Paragraph({ text: "" }));
        children.push(new docx.Paragraph({ text: "This document provides a draft implementation protocol for this project." }));
        children.push(new docx.Paragraph({ text: "" }));
        children.push(new docx.Paragraph({ text: "Context (summary): " + contextText }));
      }
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "2. Cadre conceptuel d'implementation" : "2. Implementation framework", heading: docx.HeadingLevel.HEADING_1 }));
      if (frameworksList.length) {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Cadres proposes pour structurer l'analyse et le suivi :" : "Proposed frameworks to structure analysis and monitoring:" }));
        frameworksList.forEach((fw) => { children.push(new docx.Paragraph({ text: "- " + fw })); });
      } else {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Aucun cadre specifique defini." : "No specific framework defined." }));
      }
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "3. Strategies d'implementation (ERIC)" : "3. Implementation strategies (ERIC)", heading: docx.HeadingLevel.HEADING_1 }));
      if (strategiesList.length) {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Liste preliminaire des strategies a mobiliser :" : "Preliminary list of strategies to be used:" }));
        strategiesList.forEach((st) => { children.push(new docx.Paragraph({ text: "- " + st })); });
      } else {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Aucune strategie ERIC n'a encore ete selectionnee." : "No ERIC strategy has been selected yet." }));
      }
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "4. Barrieres et leviers" : "4. Barriers and enablers", heading: docx.HeadingLevel.HEADING_1 }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "Barrieres principales identifiees :" : "Main barriers identified:" }));
      children.push(new docx.Paragraph({ text: barriersText }));
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "Note : completer en atelier les barrieres, leviers potentiels et hypotheses sur les mecanismes d'implementation." : "Note: complete in workshop with enablers and hypotheses about implementation mechanisms." }));
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "5. Resultats d'implementation vises (Proctor)" : "5. Target implementation outcomes (Proctor)", heading: docx.HeadingLevel.HEADING_1 }));
      if (outcomesList.length) {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Resultats d'implementation a suivre :" : "Implementation outcomes to be monitored:" }));
        outcomesList.forEach((oc) => { children.push(new docx.Paragraph({ text: "- " + oc })); });
      } else {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "Aucun resultat d'implementation n'a encore ete defini." : "No implementation outcomes have been defined yet." }));
      }
      children.push(new docx.Paragraph({ text: "" }));
      if (recommendationsList.length) {
        children.push(new docx.Paragraph({ text: lang === "fr" ? "6. Recommandations contextuelles" : "6. Contextual recommendations", heading: docx.HeadingLevel.HEADING_1 }));
        recommendationsList.forEach((rec) => { children.push(new docx.Paragraph({ text: "- " + rec })); });
        children.push(new docx.Paragraph({ text: "" }));
      }
      children.push(new docx.Paragraph({ text: lang === "fr" ? "7. Plan d'action initial (a completer)" : "7. Initial action plan (to be completed)", heading: docx.HeadingLevel.HEADING_1 }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "Proposez 3 a 5 actions concretes pour lancer l'implementation (activite, responsable, echeance, indicateurs de suivi)." : "Define 3-5 concrete actions to launch implementation (activity, responsible person, deadline, follow-up indicators)." }));
      children.push(new docx.Paragraph({ text: "" }));
      const headerCells = [lang === "fr" ? "Activite" : "Activity", lang === "fr" ? "Responsable" : "Owner", lang === "fr" ? "Echeance" : "Deadline", lang === "fr" ? "Indicateur" : "Indicator"];
      const tableRows = [new docx.TableRow({ children: headerCells.map((t) => new docx.TableCell({ children: [new docx.Paragraph({ text: t })] })) })];
      for (let i = 0; i < 5; i++) {
        tableRows.push(new docx.TableRow({ children: [0, 1, 2, 3].map(() => new docx.TableCell({ children: [new docx.Paragraph({ text: "" })] })) }));
      }
      children.push(new docx.Table({ rows: tableRows }));
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: lang === "fr" ? "8. Notes pour decrire l'intervention (TIDieR)" : "8. Notes to describe the intervention (TIDieR-style)", heading: docx.HeadingLevel.HEADING_1 }));
      const tidierItems = lang === "fr"
        ? ["- Nom et raison d'etre de l'intervention :", "", "- Qui fait quoi (profils, roles) :", "", "- Comment l'intervention est-elle delivree (canaux, frequence, duree) :", "", "- Adaptations prevues selon les contextes :", "", "- Suivi de la fidelite (ce qui est bien applique / moins applique) :"]
        : ["- Name and rationale of the intervention:", "", "- Who does what (profiles, roles):", "", "- How the intervention is delivered (channels, frequency, duration):", "", "- Planned adaptations across contexts:", "", "- How fidelity will be monitored:"];
      tidierItems.forEach((t) => { children.push(new docx.Paragraph({ text: t })); });
      children.push(new docx.Paragraph({ text: "" }));
      children.push(new docx.Paragraph({ text: "---" }));
      children.push(new docx.Paragraph({ text: "Moudar v8.0 - Younes MOUDAR - contact@moudar.com", alignment: docx.AlignmentType.CENTER }));
      const doc = new docx.Document({ sections: [{ children }] });
      docx.Packer.toBlob(doc).then((blob) => {
        const dateStr = new Date().toISOString().split("T")[0];
        saveAs(blob, "Protocol_" + (answers.title || "Moudar").replace(/\s+/g, "_") + "_" + dateStr + ".docx");
      }).catch((err) => {
        console.error("[MOUDAR] Erreur export Word:", err);
        alert(lang === "fr" ? "Erreur lors de l'export Word" : "Error during Word export");
      });
    } catch (e) {
      console.error("[MOUDAR] Erreur export Word:", e);
      alert(lang === "fr" ? "Erreur lors de l'export Word: " + e.message : "Error during Word export: " + e.message);
    }
  };

  // Show protocol if already generated
  if (protocol && step === -1) {
    setStep(questions.length);
  }

  // ═══════════════════════════════════════
  // PROTOCOL VIEW (when protocol is set)
  // ═══════════════════════════════════════
  if (protocol) {
    return (<div className="max-w-3xl mx-auto fade-in">
      {/* __WIZARD_PROTOCOL_VIEW_PLACEHOLDER__ */}
      <div className="flex justify-between items-center mb-4">
        <button onClick={() => { setProtocol(null); setStep(0); }} className="text-blue-600 hover:text-blue-800">{"\u2190 "}{lang === "fr" ? "Modifier les r\u00e9ponses" : "Edit answers"}</button>
        <div className="flex gap-2">
          <button onClick={saveProject} aria-label={lang === "fr" ? "Sauvegarder ce projet" : "Save this project"} className={"px-4 py-2 text-white rounded-lg text-sm transition " + (saved ? "bg-green-600" : "bg-gray-600 hover:bg-gray-700")}>{saved ? "\u2713 " + (lang === "fr" ? "Sauvegard\u00e9" : "Saved") : "\uD83D\uDCBE " + (lang === "fr" ? "Sauvegarder" : "Save")}</button>
          <button onClick={exportWord} aria-label={lang === "fr" ? "Exporter le protocole en Word" : "Export protocol to Word"} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition">{"\uD83D\uDCDD Word"}</button>
        </div>
      </div>
      <div className="bg-white rounded-xl shadow-xl overflow-hidden">
        <div className="gradient-hero p-6 text-white">
          <h2 className="text-2xl font-bold mb-1">{answers.title}</h2>
          <p className="text-white/80">{answers.organization}</p>
          <div className="flex gap-2 mt-3">
            <span className="px-2 py-1 bg-white/20 rounded text-sm">{DOMAINS[answers.domain] ? DOMAINS[answers.domain].icon + " " + tObj(DOMAINS[answers.domain], lang) : ""}</span>
            <span className="px-2 py-1 bg-white/20 rounded text-sm">{PHASES[answers.phase] ? PHASES[answers.phase].icon + " " + tObj(PHASES[answers.phase], lang) : ""}</span>
          </div>
        </div>
        <div className="p-6 space-y-6">
          {/* Protocol content sections rendered by ProtocolContentSection below */}
        </div>
      </div>
      <FeedbackModal />
      {/* All modal views */}
      {showTheory && <TheoryOfChangeView project={answers} protocol={protocol} lang={lang} onClose={() => setShowTheory(false)} />}
      {showScenarios && <ScenarioComparatorView project={answers} lang={lang} onClose={() => setShowScenarios(false)} onSelectScenario={(result) => { const newProtocol = Object.assign({}, protocol); newProtocol.strategies = result.strategies.map((s) => s.label[lang]); newProtocol.aiRawRecommendations = Object.assign({}, protocol.aiRawRecommendations, { strategies: Object.assign({}, protocol.aiRawRecommendations.strategies, { top: result.strategies }) }); newProtocol.selectedScenario = result.scenario.id; setProtocol(newProtocol); setShowScenarios(false); setSaved(false); }} />}
      {showKPIs && protocol.aiRawRecommendations && <KPIPanelView strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowKPIs(false)} />}
      {showStakeholders && <StakeholderMapModal project={answers} protocol={protocol} lang={lang} onClose={() => setShowStakeholders(false)} onSave={(stakeholders) => { setAnswers(Object.assign({}, answers, { stakeholders })); setSaved(false); }} />}
      {showTrainingPlan && <TrainingPlanView project={answers} protocol={protocol} lang={lang} onClose={() => setShowTrainingPlan(false)} />}
      {showSuccessPrediction && protocol && protocol.aiRawRecommendations && <SuccessPredictionView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowSuccessPrediction(false)} />}
      {showBudgetEstimator && protocol && protocol.aiRawRecommendations && <BudgetEstimatorView project={answers} protocol={{ strategies: protocol.aiRawRecommendations.strategies.top }} lang={lang} onClose={() => setShowBudgetEstimator(false)} />}
      {showCountryIntelligence && <CountryIntelligenceView project={answers} lang={lang} onClose={() => setShowCountryIntelligence(false)} onSelectCountry={(countryCode) => { setAnswers(Object.assign({}, answers, { country: countryCode })); setSaved(false); }} />}
      {showCaseLibrary && <CaseLibraryView project={answers} protocol={protocol} lang={lang} onClose={() => setShowCaseLibrary(false)} />}
      {showRiskAnalysis && protocol && protocol.aiRawRecommendations && <RiskAnalysisView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowRiskAnalysis(false)} />}
      {showResearchExports && protocol && protocol.aiRawRecommendations && <ResearchExportsView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowResearchExports(false)} />}
      {showTornadoAnalysis && protocol && <TornadoAnalysisView project={Object.assign({}, answers, { barriers: protocol.aiRawRecommendations ? protocol.aiRawRecommendations.metadata.detectedBarriers || answers.barrierCategories || [] : answers.barrierCategories || [], phase: answers.phase, resourceLevel: answers.country ? answers.country.indexOf("morocco") !== -1 || answers.country.indexOf("tunisia") !== -1 ? "R03" : answers.country.indexOf("senegal") !== -1 || answers.country.indexOf("mali") !== -1 ? "R04" : "R02" : "R03" })} lang={lang} onClose={() => setShowTornadoAnalysis(false)} />}
      {showPortfolio && <PortfolioView projects={StorageManager.getAllProjects()} lang={lang} onClose={() => setShowPortfolio(false)} onSelectProject={() => setShowPortfolio(false)} />}
      {showGanttTimeline && protocol && protocol.aiRawRecommendations && <GanttTimelineView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowGanttTimeline(false)} />}
      {showCFIR2 && protocol && protocol.aiRawRecommendations && <CFIR2View project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowCFIR2(false)} />}
      {showREAIM && protocol && protocol.aiRawRecommendations && <REAIMView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowREAIM(false)} />}
      {showROICalculator && protocol && <ROICalculatorView project={answers} budget={MoudarEngine.estimateBudget(answers, protocol.aiRawRecommendations ? protocol.aiRawRecommendations.strategies.top : [], lang)} lang={lang} onClose={() => setShowROICalculator(false)} />}
      {showFundingProposal && protocol && protocol.aiRawRecommendations && <FundingProposalView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} budget={MoudarEngine.estimateBudget(answers, protocol.aiRawRecommendations.strategies.top, lang)} lang={lang} onClose={() => setShowFundingProposal(false)} />}
      {showMonitoringDashboard && protocol && protocol.aiRawRecommendations && <MonitoringDashboardView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowMonitoringDashboard(false)} />}
      {showLogicModel && protocol && protocol.aiRawRecommendations && <LogicModelView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowLogicModel(false)} />}
      {showMonteCarlo && protocol && protocol.aiRawRecommendations && <MonteCarloView project={answers} strategies={protocol.aiRawRecommendations.strategies.top} lang={lang} onClose={() => setShowMonteCarlo(false)} />}
      {showNLPAnalyzer && <NLPBarrierAnalyzerView project={answers} lang={lang} onClose={() => setShowNLPAnalyzer(false)} />}
      {showPowerPointGenerator && protocol && <PowerPointGeneratorView project={answers} protocol={protocol} lang={lang} onClose={() => setShowPowerPointGenerator(false)} />}
      {showAPIDocs && <APIDocumentationView lang={lang} onClose={() => setShowAPIDocs(false)} />}
      {showCommunityHub && <CommunityHubView project={answers} lang={lang} onClose={() => setShowCommunityHub(false)} />}
      {showDataIntegrations && <DataIntegrationsView project={answers} protocol={protocol} lang={lang} onClose={() => setShowDataIntegrations(false)} />}
      {showXAIExplainer && <XAIExplainerView protocol={protocol} answers={answers} lang={lang} onClose={() => setShowXAIExplainer(false)} />}
      {showGlossary && <GlossaryView lang={lang} onClose={() => setShowGlossary(false)} />}
      {showCertification && <CertificationView protocol={protocol} answers={answers} lang={lang} onClose={() => setShowCertification(false)} />}
      {showDocumentAnalyzer && <DocumentAnalyzerView lang={lang} onClose={() => setShowDocumentAnalyzer(false)} />}
    </div>);
  }

  // ═══════════════════════════════════════
  // WIZARD FORM VIEW (step-by-step)
  // ═══════════════════════════════════════
  const currentQ = questions[step];
  const progress = (step + 1) / questions.length * 100;
  const phases = [
    { name: { fr: "Projet", en: "Project" }, icon: "\uD83D\uDCCB", questions: [0, 1, 2] },
    { name: { fr: "Contexte", en: "Context" }, icon: "\uD83C\uDFE2", questions: [3, 4] },
    { name: { fr: "Cibles", en: "Targets" }, icon: "\uD83C\uDFAF", questions: [5] },
    { name: { fr: "Barri\u00e8res", en: "Barriers" }, icon: "\u26A0\uFE0F", questions: [6] }
  ];
  let currentPhase = phases.findIndex((p) => p.questions.includes(step));
  if (currentPhase < 0) currentPhase = 3;

  return (
    <div className="max-w-lg mx-auto fade-in">
      <div className="text-center mb-4">
        <h2 className="text-xl font-bold text-gray-800">{"\u2728 "}{lang === "fr" ? "Assistant de conception" : "Design Assistant"}</h2>
        <p className="text-gray-500 text-sm">{lang === "fr" ? "En 10-15 minutes, obtenez un squelette de protocole" : "In 10-15 minutes, get a protocol skeleton"}</p>
      </div>
      <div className="flex justify-between items-center mb-6 px-4">
        {phases.map((phase, i) => {
          const isActive = i === currentPhase;
          const isCompleted = i < currentPhase;
          return (
            <div key={i} className="flex flex-col items-center flex-1">
              <div className="flex items-center w-full">
                <div className={"w-10 h-10 rounded-full flex items-center justify-center text-lg font-bold transition-all " + (isCompleted ? "bg-green-500 text-white" : isActive ? "bg-purple-600 text-white ring-4 ring-purple-200" : "bg-gray-200 text-gray-500")}>{isCompleted ? "\u2713" : phase.icon}</div>
                {i < phases.length - 1 && <div className={"flex-1 h-1 mx-2 rounded " + (i < currentPhase ? "bg-green-500" : "bg-gray-200")} />}
              </div>
              <span className={"text-xs mt-1 font-medium " + (isActive ? "text-purple-700" : "text-gray-500")}>{phase.name[lang]}</span>
            </div>
          );
        })}
      </div>
      <div className="h-2 bg-gray-200 rounded-full mb-4">
        <div className="h-2 bg-purple-500 rounded-full transition-all" style={{ width: progress + "%" }} />
      </div>
      <div className="bg-white rounded-xl shadow-xl p-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="w-8 h-8 bg-purple-100 text-purple-700 rounded-full flex items-center justify-center font-bold text-sm">{step + 1}</span>
          <h3 className="font-bold text-gray-800">{currentQ.q}</h3>
        </div>
        {currentQ.type === "text" && (
          <input type="text" value={answers[currentQ.id] || ""} onChange={(e) => { const na = Object.assign({}, answers); na[currentQ.id] = e.target.value; setAnswers(na); }} className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:outline-none transition" placeholder={currentQ.placeholder || ""} />
        )}
        {currentQ.type === "textarea" && (
          <textarea value={answers[currentQ.id] || ""} onChange={(e) => { const na = Object.assign({}, answers); na[currentQ.id] = e.target.value; setAnswers(na); }} rows={currentQ.rows || 4} className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:outline-none transition" placeholder={currentQ.placeholder || ""} />
        )}
        {currentQ.type === "select" && (
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {currentQ.options.map((opt) => {
              const isSelected = answers[currentQ.id] === opt.value;
              return (
                <button key={opt.value} onClick={() => { const na = Object.assign({}, answers); na[currentQ.id] = opt.value; setAnswers(na); }} className={"w-full text-left p-3 rounded-xl border-2 transition " + (isSelected ? "border-purple-500 bg-purple-50" : "border-gray-200 hover:border-gray-300")}>
                  <span className="font-medium">{opt.label}</span>
                  {currentQ.showDescription && opt.description && <p className="text-xs text-gray-500 mt-1">{opt.description}</p>}
                </button>
              );
            })}
          </div>
        )}
        {currentQ.type === "number" && (
          <input type="number" value={answers[currentQ.id] || ""} onChange={(e) => { const na = Object.assign({}, answers); na[currentQ.id] = e.target.value ? parseInt(e.target.value) : ""; setAnswers(na); }} min={currentQ.min || 1} max={currentQ.max || 999999} className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:outline-none transition" placeholder={currentQ.placeholder || ""} />
        )}
        {currentQ.type === "multiselect" && (
          <div className="space-y-2 max-h-72 overflow-y-auto">
            <p className="text-xs text-gray-500 mb-2">
              {lang === "fr" ? "S\u00e9lectionnez " + (currentQ.minSelect || 1) + " \u00e0 " + (currentQ.maxSelect || 5) + " options" : "Select " + (currentQ.minSelect || 1) + " to " + (currentQ.maxSelect || 5) + " options"}{" \u2022 "}
              <span className="font-medium">{(answers[currentQ.id] || []).length} {lang === "fr" ? "s\u00e9lectionn\u00e9(s)" : "selected"}</span>
            </p>
            {currentQ.options.map((opt) => {
              const currentSelections = answers[currentQ.id] || [];
              const isSelected = currentSelections.indexOf(opt.value) !== -1;
              const canSelect = currentSelections.length < (currentQ.maxSelect || 5) || isSelected;
              return (
                <button key={opt.value} onClick={() => { if (!canSelect && !isSelected) return; const na = Object.assign({}, answers); let selections = na[currentQ.id] ? na[currentQ.id].slice() : []; if (isSelected) { selections = selections.filter((v) => v !== opt.value); } else { selections.push(opt.value); } na[currentQ.id] = selections; setAnswers(na); }} disabled={!canSelect && !isSelected} className={"w-full text-left p-3 rounded-xl border-2 transition flex items-center gap-3 " + (isSelected ? "border-purple-500 bg-purple-50" : canSelect ? "border-gray-200 hover:border-gray-300" : "border-gray-100 bg-gray-50 opacity-50 cursor-not-allowed")}>
                  <span className={"w-5 h-5 rounded border-2 flex items-center justify-center " + (isSelected ? "border-purple-500 bg-purple-500 text-white" : "border-gray-300")}>{isSelected && "\u2713"}</span>
                  <span className="font-medium">{opt.label}</span>
                </button>
              );
            })}
          </div>
        )}
        {currentQ.help && <p className="mt-3 text-sm text-gray-500 flex items-start gap-2"><span>{"\uD83D\uDCA1"}</span><span>{currentQ.help}</span></p>}
        <div className="mt-2 flex items-center gap-2">
          {currentQ.required !== false
            ? <span className="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded">{lang === "fr" ? "Obligatoire" : "Required"}</span>
            : <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded">{lang === "fr" ? "Optionnel" : "Optional"}</span>}
        </div>
        {qualityScore && (
          <div className={"mt-4 p-3 rounded-lg border " + (qualityScore.color === 'green' ? 'bg-green-50 border-green-200' : qualityScore.color === 'blue' ? 'bg-blue-50 border-blue-200' : qualityScore.color === 'yellow' ? 'bg-yellow-50 border-yellow-200' : 'bg-red-50 border-red-200')}>
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">{lang === "fr" ? "Qualit\u00e9 des donn\u00e9es:" : "Data quality:"}</span>
              <span className={"font-bold " + (qualityScore.color === 'green' ? 'text-green-700' : qualityScore.color === 'blue' ? 'text-blue-700' : qualityScore.color === 'yellow' ? 'text-yellow-700' : 'text-red-700')}>{qualityScore.score}% - {qualityScore.label[lang]}</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
              <div className={"h-2 rounded-full " + (qualityScore.color === 'green' ? 'bg-green-500' : qualityScore.color === 'blue' ? 'bg-blue-500' : qualityScore.color === 'yellow' ? 'bg-yellow-500' : 'bg-red-500')} style={{ width: qualityScore.score + '%' }} />
            </div>
          </div>
        )}
        {validationErrors && validationErrors.length > 0 && (
          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex items-center text-red-800 font-semibold mb-2"><span className="mr-2">{"\u26A0\uFE0F"}</span>{lang === "fr" ? "Donn\u00e9es insuffisantes" : "Insufficient data"}</div>
            <p className="text-sm text-red-700 mb-2">{lang === "fr" ? "Veuillez corriger les erreurs suivantes pour g\u00e9n\u00e9rer un protocole fiable:" : "Please correct the following errors to generate a reliable protocol:"}</p>
            <ul className="text-sm text-red-600 space-y-1">
              {validationErrors.map((err, idx) => (
                <li key={idx} className="flex items-start"><span className="mr-2">{"\u2022"}</span><span><strong>{err.field + ": "}</strong>{err.message}</span></li>
              ))}
            </ul>
            <button onClick={() => setValidationErrors(null)} className="mt-3 text-xs text-red-600 hover:text-red-800 underline">{lang === "fr" ? "Fermer" : "Close"}</button>
          </div>
        )}
        <div className="flex justify-between mt-6">
          <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} className="px-4 py-2 text-gray-600 disabled:opacity-50 hover:text-gray-800 transition">{"\u2190 "}{lang === "fr" ? "Pr\u00e9c\u00e9dent" : "Previous"}</button>
          {step < questions.length - 1
            ? <button onClick={() => setStep(step + 1)} className="px-6 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition">{lang === "fr" ? "Suivant" : "Next"}{" \u2192"}</button>
            : <button onClick={generateProtocol} disabled={isGenerating} className={"px-6 py-2 text-white rounded-xl transition " + (isGenerating ? "bg-gray-500 cursor-wait" : "bg-green-600 hover:bg-green-700")}>
                {isGenerating
                  ? <span className="flex items-center gap-2"><svg className="animate-spin h-4 w-4" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>{lang === "fr" ? "G\u00e9n\u00e9ration IA..." : "AI Generation..."}</span>
                  : <span>{"\u2728 "}{lang === "fr" ? "G\u00e9n\u00e9rer le protocole" : "Generate protocol"}</span>}
              </button>}
        </div>
      </div>
    </div>
  );
}
